### ISSUE TITLE
Unhandled exception when launching

### ISSUE THREAD

**Issue by adamelders** [Assistant/ModAssistant#52]
When launching Mod Assistant 1.0.2.5, Beat Saber version 1.42, I get the following error:

![image](https://user-images.githubusercontent.com/17323832/67246594-df15d880-f42c-11e9-8320-67d62d1fd97c.png)

**Comment by IcicleTrepan** [comment]
I am suddenly getting the same error

**Comment by Assistant** [comment]
I'm not certain what is causing that, and I won't have a testing environment for a little bit.

However, people have said that changing the directory where it's run and disabling installed mods detection works as a temporary workaround.

**Comment by Assistant** [comment]
The issue was on BeatMods' side, should be fixed now.

**Comment by dvanw6** [comment]
Yeah no, its not fixed I am bloody trying to get the mod assistant to work but every time its sending that same bloody error saying either the IPA.exe is in use or the bloody songe-converter.exe is in use, AND THATS JUST TRYING TO INSTALL THE 2 DEFAULT MODS! Bloody fix this already.

**Comment by dvanw6** [comment]
Oh my word this program is so stupid, it keeps on saying another process is using the program, WHEN IT IS THE OTHER PROCESS THAT IS USING THE PROGRAM, HOW STUPID CAN IT GET

**Comment by Assistant** [comment]
That sounds like a completely different issue. Try disabling your AV and seeing if that works.

**Comment by dvanw6** [comment]
It didnt work
